---
deployment:
  tasks:
    # 1. Deploy Frontend (Visuals)
    # Takes the 'dist' folder you build locally and puts it in the live site
    - export FRONTENDPATH=/home/zahhnpez/public_html/
    - /bin/cp -R dist/* $FRONTENDPATH

    # 2. Deploy Backend (Logic)
    # Copies ONLY the backend folder so we don't overwrite server configs (passenger_wsgi.py)
    - export BACKENDPATH=/home/zahhnpez/api_backend/
    - /bin/cp -R kipekee-backend $BACKENDPATH
